"""Is active field is added in profile

Revision ID: 18aaf2539bd5
Revises: 70f55ad072bf
Create Date: 2024-09-15 17:08:26.586277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18aaf2539bd5'
down_revision: Union[str, None] = '70f55ad072bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'is_active')
    # ### end Alembic commands ###
