"""Is active field is added in post model

Revision ID: 2c2a37ad5ec3
Revises: 18aaf2539bd5
Create Date: 2024-09-16 09:18:58.711598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2a37ad5ec3'
down_revision: Union[str, None] = '18aaf2539bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_active')
    # ### end Alembic commands ###
