"""Is active field is added in chat model

Revision ID: 4783137a12d6
Revises: 2c2a37ad5ec3
Create Date: 2024-09-16 09:44:15.985679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4783137a12d6'
down_revision: Union[str, None] = '2c2a37ad5ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'is_active')
    # ### end Alembic commands ###
