"""add cascade for both delete and update

Revision ID: 95b87241e019
Revises: 60087d19fa22
Create Date: 2024-09-12 14:04:34.468192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b87241e019'
down_revision: Union[str, None] = '60087d19fa22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_ibfk_1', 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'registration', ['registration_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key('profile_ibfk_1', 'profile', 'registration', ['registration_id'], ['id'])
    # ### end Alembic commands ###
