"""profile id is add in post model

Revision ID: ee3dca5d36cc
Revises: 014209aae81f
Create Date: 2024-09-13 13:40:02.839692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3dca5d36cc'
down_revision: Union[str, None] = '014209aae81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'profile', ['profile_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'profile_id')
    # ### end Alembic commands ###
