"""add relationship between profile and posts

Revision ID: ee9e678170ee
Revises: ee3dca5d36cc
Create Date: 2024-09-13 14:52:39.916105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9e678170ee'
down_revision: Union[str, None] = 'ee3dca5d36cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
